apiVersion: v2
name: voting-system
version: 0.1.0
appVersion: "0.1.0"
description: Helm chart for Secure Voting System (frontend, backend, database)

dependencies:
  - name: postgresql
    version: "13.2.24"  # <--- Newer version with valid images
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
