apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8srequiredlimits
spec:
  crd:
    spec:
      names:
        kind: K8sRequiredLimits
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srequiredlimits
        violation[{
          "msg": msg,
        }] {
          input.review.kind.kind == "Pod"
          c := input.review.object.spec.containers[_]
          not has_field(c.resources.limits, "cpu")
          msg := "CPU limit must be set"
        }
        violation[{
          "msg": msg,
        }] {
          input.review.kind.kind == "Pod"
          c := input.review.object.spec.containers[_]
          not has_field(c.resources.limits, "memory")
          msg := "Memory limit must be set"
        }
        has_field(obj, field) {
          obj[field]
        }
