apiVersion: v1
kind: Service
metadata:
  name: voting-frontend
  labels:
    app: secure-voting
    component: frontend
spec:
  selector:
    app: secure-voting
    component: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  type: ClusterIP
