apiVersion: v1
kind: Service
metadata:
  name: voting-postgres
  labels:
    app: secure-voting
    component: database
spec:
  selector:
    app: secure-voting
    component: database
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  type: ClusterIP
