apiVersion: v1
kind: Secret
metadata:
  name: voting-secrets
  labels:
    app: secure-voting
    component: secrets
type: Opaque
data:
  # base64-encoded values; replace in real deployments
  database_url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHZvdGluZy1wb3N0Z3Jlczo1NDMyL3ZvdGluZw==
  secret_key: Y2hhbmdlLW1lLXRvLWEtdmVyeS1zZWN1cmUtc3RyaW5n
  postgres_password: cG9zdGdyZXM=
  vote_encryption_key: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
