apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sNonRoot
metadata:
  name: nonroot-all-pods
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces:  # ⬅️ ADD THIS
      - kube-system
      - gatekeeper-system
      - kyverno
    namespaceSelector:
      matchExpressions:
        - key: name
          operator: NotIn
          values: ["voting-system"]  # Exclude voting-system for postgres
