apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting-system.fullname" . }}-postgres
  labels:
    app: {{ include "voting-system.name" . }}
    component: database
spec:
  selector:
    app: {{ include "voting-system.name" . }}
    component: database
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  type: ClusterIP
